---
# tasks file for roles/ntp
- name: Install ntp
  apt:
    name: ntp
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: ntp.conf template
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ntp
