---
# tasks file for roles/updates
- name: Check for updates
  apt:
    update_cache: yes

- name: Upgrade server
  apt:
    upgrade: dist

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot
  when: reboot_server

- name: Reboot server
  command: /sbin/reboot
  when: reboot.exists == true and reboot_server
