---
# tasks file for users
- include: users.yml
  tags:
    - setup_users
    - users
  when: >
        create_local_users and
        create_users is defined

- include: manage_ssh_keys.yml
  tags:
    - manage_ssh_keys
  when: >
        enable_manage_ssh_keys is defined and
        enable_manage_ssh_keys
