---
- name: Update Aptitude
  apt: update_cache=yes cache_valid_time=3600

- name: Install goodies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - screen
    - tmux
    - dnsutils
    - nmap
    - tshark
    - sshguard
    - etckeeper
    - jwhois

- name: Create account for buraglio
  user:
    name: buraglio
    shell: /bin/bash
    groups: "{{ item }}"
    append: yes
    state: present
    password: $6$Y/yEFkcLXcuAaQ$EY3dBMxqPzh9gdt7qWBu4hC0YVOtIVfyvHev.7.oCfwGn4fOABzSKtraENtJZ4Zbt9gRYedwDT.zjnRy0
  with_items:
    - adm
    - dialout
    - cdrom
    - sudo
    - audio
    - video
    - plugdev
    - games
    - users
    - netdev
    - gpio
    - i2c
    - spi
    - input

- name: Add SSH keys for buraglio
  authorized_key:
    user: buraglio
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEArAVEOYF8qGTLIzA6yerBNv8E6d86BBToxxFQMb8oIoiJCuCJGFgDUFB0xL9IuuyQGHcLakb+OuH2civORW6ftdtpEL2Yy+mUn+/3KiIDxnHJ      rXqnoTNFEvkXEfq8W8nAIztEe2wMt4g0xWvATWCGuPl9iOtw7YYMypY9Ga5YctE= buraglio@heelflip.209.buraglio.com"
